www/apps/auth/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth import views as auth_views
from forms import AuthenticationForm

### copied straight from django-registration registration.auth_urls

urlpatterns = patterns('',
    url(r'^login/$',
       auth_views.login,
       {
            'authentication_form': AuthenticationForm,
            'template_name': 'auth/login.html'
       },
       name='auth_login'),
       
    url(r'^logout/$',
       auth_views.logout,
       {'template_name': 'landing/main.html'},
       name='auth_logout'),
       
    url(r'^password/change/$',
       auth_views.password_change,
       {'template_name': 'auth/password_change_form.html'},
       name='auth_password_change'),
       
    url(r'^password/change/done/$',
       auth_views.password_change_done,
       {'template_name': 'profiles/profile_private_view.html'},
       name='auth_password_change_done'),
       
    # a password reset is requested and the form allows an email address input
    url(r'^password/reset/$',
       auth_views.password_reset,
       {
       'template_name': 'auth/password_reset_form.html',
        'email_template_name': 'auth/password_reset_email.txt',
       },
       name='auth_password_reset'),
    
    # an email has been sent to the provided email address with the link to reset password
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'auth/password_reset_done.html'},
       name='auth_password_reset_done'),
       
    # password reset link has been clicked on, forms allows for a new password and confirmation   
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
       auth_views.password_reset_confirm,
       {'template_name': 'auth/password_reset_confirm.html'},
       name='auth_password_reset_confirm'),
       
    # system has changed the password and redirect to this template for the final success message
    url(r'^password/reset/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'auth/password_reset_complete.html'},
       name='auth_password_reset_complete'),
)

www/apps/portal/models.py
#

www/apps/profiles/models/job.py
import datetime
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.contrib.auth.models import User
from uuslug import uuslug as slugify

class JobPost(models.Model):
    """
    Employer's job post
    """
    YES = 1
    NO = 2
    YES_NO_CHOICES = (
        (YES, 'Yes'),
        (NO, 'No'),
    )
    
    JOB_OPTION_FULL_TIME = 1
    JOB_OPTION_PART_TIME = 2
    JOB_OPTION_FREELANCE = 3
    JOB_OPTION_CHOICES = (
        (JOB_OPTION_FULL_TIME, 'Full-time'),
        (JOB_OPTION_PART_TIME, 'Part-time'),
        (JOB_OPTION_FREELANCE, 'Freelance'),
    )
    
    SALARY_WAGE_EXPERIENCE = 1
    SALARY_WAGE_NEGOTIABLE = 2
    SALARY_WAGE_10_100_USD = 3
    SALARY_WAGE_100_200_USD = 4
    SALARY_WAGE_200_300_USD = 5
    SALARY_WAGE_300_400_USD = 6
    SALARY_WAGE_400_500_USD = 7
    SALARY_WAGE_500_600_USD = 8
    SALARY_WAGE_600_700_USD = 9
    SALARY_WAGE_700_800_USD = 10
    SALARY_WAGE_800_900_USD = 11
    SALARY_WAGE_900_1000_USD = 12
    SALARY_WAGE_1000_1500_USD = 13
    SALARY_WAGE_1500_2000_USD = 14
    SALARY_WAGE_2000_3000_USD = 15
    SALARY_WAGE_3000_PLUS_USD = 16
    SALARY_WAGE_CHOICES = (
        (SALARY_WAGE_EXPERIENCE, 'Based on experience'),
        (SALARY_WAGE_NEGOTIABLE, 'Negotiable'),
        (SALARY_WAGE_10_100_USD, '10-100 USD'),
        (SALARY_WAGE_100_200_USD, '100-200 USD'),
        (SALARY_WAGE_200_300_USD, '200-300 USD'),
        (SALARY_WAGE_300_400_USD, '300-400 USD'),
        (SALARY_WAGE_400_500_USD, '400-500 USD'),
        (SALARY_WAGE_500_600_USD, '500-600 USD'),
        (SALARY_WAGE_600_700_USD, '600-700 USD'),
        (SALARY_WAGE_700_800_USD, '700-800 USD'),
        (SALARY_WAGE_800_900_USD, '800-900 USD'),
        (SALARY_WAGE_900_1000_USD, '900-1000 USD'),
        (SALARY_WAGE_1000_1500_USD, '1000-1500 USD'),
        (SALARY_WAGE_1500_2000_USD, '1500-2000 USD'),
        (SALARY_WAGE_2000_3000_USD, '2000-3000 USD'),
        (SALARY_WAGE_3000_PLUS_USD, '3000 + USD'),
    )
    
    user = models.ForeignKey(
                User,
                related_name="%(class)s",
                null=False
    )

    title = models.CharField(
                _('Job Title'), 
                blank=False, 
                max_length=56,
                help_text = _("Title of this job post (e.g. PHP developer, Marketing Manager)")
    )

    slug = models.CharField(
                _('Slug'), 
                blank=True, 
                max_length=200,
                help_text = _("Slug will be auto generated)")
    )
        
    description = models.TextField(
                _('Job Description'), 
                blank=False, 
                validators=[MinLengthValidator(25), MaxLengthValidator(750)],
                help_text = _("Detailed description of this jobs post")
    )


    requirements = models.TextField(
                _('Job Requirements'), 
                blank=True, 
                validators=[MinLengthValidator(25), MaxLengthValidator(750)],
                help_text = _("Detailed requirements for this job posts. (highly recommended)")
    )
    
    keywords = models.CharField(
                _('Related Keywords, Tags'), 
                blank=True,
                max_length=56,
                help_text = _("Job related keywords that makes the job easier to find. (e.g. English Wordpress HTML CSS PHP Article)")
    )
    
    contact = models.CharField(
                _('Job Contact Info'), 
                blank=True,
                max_length=56,
                help_text = _("Email or Number so jobseekers can contact you. OR leave blank to use your profile email")
    )
    
    employment_option = models.IntegerField(
                _('Employment Option'), 
                choices=JOB_OPTION_CHOICES, 
                blank=False,
                null=True,
                help_text = _("Full-time = dedicated stuff, Part-time = shared staff, Freelance = per project")
    )
    
    wage_salary = models.IntegerField(
                _('Salary'),
                choices=SALARY_WAGE_CHOICES, 
                blank=False,
                null=True,
                help_text = _("Monthly salary budget for this job")
    )
    
    start_date = models.DateField(
                _('Start Date'), 
                default=datetime.date.today(), 
                help_text = _("Start date. Select today for immediate start date -- format [YYYY-MM-DD]")
    )

    viewed = models.IntegerField(
                _('Number views'),
                default=0,
                help_text = _("How many people have viewed this job")
    )

    bookmarked = models.IntegerField(
                _('Number bookmarks'),
                default=0,
                help_text = _("How many people have bookmarked this job")
    )
        
    is_active = models.IntegerField(
                _('Active'),
                choices=YES_NO_CHOICES, 
                default=YES,
                help_text = _("Yes for active jobs.  No for hidden, non-active job posts")
    )
    
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    
    class Meta:
        app_label = 'profiles'
        unique_together = (("user", "title"),)
        ordering = ['title',]


    def __unicode__(self):
        return u'%s' % self.title

    def get_absolute_url(self):
        return "/job/%d/%s/" % (self.id, self.get_slug)
    
    @property
    def get_slug(self):
        return str(self.slug)

    @property
    def is_public(self):
        return self.is_active == self.YES

    @property
    def is_past_due(self):
        return datetime.date.today() >= self.start_date

    def just_viewed(self):
        self.viewed += 1
        self.save()
        return self.viewed
            
    def set_bookmark(self, increment=True):
        if increment:
            self.bookmarked += 1
        elif self.bookmarked > 0:
            self.bookmarked -= 1
        self.save()
        return self.bookmarked

    @property
    def is_complete(self):
        if self.title and self.description:
            return True
        return False
        
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title[:100])
        if not self.slug:
            self.slug = 'job' # ensure no empty slug
        p = self.user.get_profile()
        if p.is_employer:
            p.posted_jobs = True
            p.save()
        return super(JobPost, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        p = self.user.get_profile()
        if p.is_employer:
            j = JobPost.objects.filter(user=self.user)
            if len(j) <= 1: # this is the last job post, and it will be deleted right now
                p.posted_jobs = False
                p.save()
        return super(JobPost, self).delete(*args, **kwargs)

www/apps/profiles/models/skill.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.contrib.auth.models import User

class SkillManager(models.Manager):
    default_name = "general"
    
    def get_query_set(self):
        return super(SkillManager, self).get_query_set().order_by('priority', 'name')

        
    def get_default_name(self):
        return self.default_name

    def get_categories(self):
        return self.filter(category__isnull=True).order_by('priority', 'name')

    def get_default_category(self):
        try:
            return self.get(category__isnull=True, name__iexact=self.default_name)
        except:
            return None

    def get_category_skills(self, category):
        return self.filter(category__name__iexact=category).order_by('priority', 'name')

    def get_default_skill_for_category(self, category):
        try:
            return self.get(category__name__iexact=category, name__iexact=self.default_name)
        except:
            return None


class Skill(models.Model):
    """
    Skill name and its parent category
    """
    name = models.CharField(
                _('Skill Name'),
                max_length=70,
                null=False
    )

    category = models.ForeignKey(
                'self',
                blank=True,
                null=True
    )

    priority = models.IntegerField(
                _('Priority'), 
                default=100,
                help_text = _("A way to show the high priority skills first")
    )

    is_active = models.BooleanField(
                default=True
    )

    objects = SkillManager()

    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    class Meta:
        app_label = 'profiles'
        ordering = ['category__name', 'name']


    def __unicode__(self):
        return u'%s' % (self.name)


class SkillSet(models.Model):
    """
    User skill with its level & user experience detail
    """
    SKILL_NUM_DETAIL_REQRD  = 5 # detail is required on the first 5 skills
    SKILL_NUM_MAX_ALLOWED   = 10 # max number of allowed skills
    SKILL_LEVEL_BEGINNER    = 1
    SKILL_LEVEL_JUNIOR      = 2
    SKILL_LEVEL_INTERMIDATE = 3
    SKILL_LEVEL_EXPERIENCED = 4
    SKILL_LEVEL_EXPERT      = 5
    SKILL_LEVEL_CHOICES = (
        (SKILL_LEVEL_BEGINNER,      'Beginner - Never done it before, just started learning'),
        (SKILL_LEVEL_JUNIOR,        'Junior - Barely done it before, not quite comfortable'),
        (SKILL_LEVEL_INTERMIDATE,   'Intermediate - Comfortable at it, lack the experience'),
        (SKILL_LEVEL_EXPERIENCED,   'Experienced - Very comfortable at it, been doing it for a while'),
        (SKILL_LEVEL_EXPERT,        'Expert - Extremely comfortable at it, looking beyond my comfort zone'),
    )

    user = models.ForeignKey(
                User,
                related_name="%(class)s",
                null=False
    )

    skill = models.ForeignKey(
                'Skill', 
                null=False
    )
    
    level = models.IntegerField(
                _('Skill Level'), 
                choices=SKILL_LEVEL_CHOICES, 
                blank=False,
                null=False,
                help_text = _("Tell others about your level of experience with this skill")
    )

    detail = models.TextField(
                _('Skill Detail'), 
                blank=True, 
                validators=[MinLengthValidator(25), MaxLengthValidator(400)],
                help_text = _("Detail is required for your first %d skills, however we recommend it for all your skills" % SKILL_NUM_DETAIL_REQRD)
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        app_label = 'profiles'
        unique_together = (("user", "skill"),)
        ordering = ['skill__category__name', 'skill__name']


    def __unicode__(self):
        if self.skill.category:
            return u'%s-%s-%s' % (self.skill.category, self.skill.name, self.SKILL_LEVEL_CHOICES[self.level-1][1])
        else:
            return u'%s-%s' % (self.skill.name, self.SKILL_LEVEL_CHOICES[self.level-1][1])
            
    def save(self, *args, **kwargs):
        p = self.user.get_profile()
        if p.is_employee:
            p.posted_skills = True
            p.save()
        return super(SkillSet, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        p = self.user.get_profile()
        if p.is_employee:
            s = SkillSet.objects.filter(user=self.user)
            if len(s) <= 1: # this is the last skill set, and it will be deleted right now
                p.posted_skills = False
                p.save()
        return super(SkillSet, self).delete(*args, **kwargs)

www/apps/bookmark/forms.py
#

www/templates/portal/bookmark_view.html
{% extends "base/base_2col.html" %}

{% block www_title %}Favorite Bookmarks for {{profile.full_name}}{% endblock www_title %}

{% block www_container_title %}
    {% include "portal/submenu.html" %}
{% endblock www_container_title %}

{% block www_content_box_1 %}
    {% include "bookmark/bookmark_private_view.html" %}
{% endblock www_content_box_1 %}

{% block www_content_box_2 %}
    {% include "bookmark/bookmark_action_private_view.html" %}
{% endblock www_content_box_2 %}

www/templates/portal/employee_object_public_view.html
{% extends "base/base_2col.html" %}

{% block www_title %}Jobseeker Profile - {{profile.full_name}} - {{profile.title}}{% endblock www_title %}

{% block www_description %}
    <meta name="description" content="Get hired by an international company. Work from the comfort of your home. Post your resume and apply for home based jobs. Our free training book will amaze you." />
{% endblock www_description %}

{% block fb_meta %}

    <meta property="og:type" content="website"/>
    <meta property="og:image" content="{{ COMMON_DOWNLOADABLE_STATIC_URL }}images/flags/{{this_user.get_profile.country|lower}}_64.png" />
    <meta property="og:site_name" content="OutsourceFacotr" />
    <meta property="og:video:height" content="640" />
    <meta property="og:video:width" content="385" />
    <meta property="og:video:type" content="video/mp4" />
    <meta property="og:video" content="{{STATIC_URL}}video/landing_jobseekers.mp4" />
    <meta property="og:title" content="Jobseeker Profile - {{profile.full_name}} - {{profile.title}}"/>
    <meta property="og:description" content="Home based jobs working from your own country. Our free ebook teaches you how to find the best online job. Employers on OutsourceFactor want to hire people in your country. It's easy to create your online profile and browse jobs "/>
    <meta property="fb:app_id" content="377544715590279"/>

{% endblock fb_meta %}

{% block www_container_title %}
    {% include "portal/submenu.html" %}
{% endblock www_container_title %}

{% block www_content_box_1 %}
    {% include "employee/employee_profile_public_view.html" %}
{% endblock www_content_box_1 %}

{% block www_content_box_2 %}
    {% include "employee/employee_action_public_view.html" %}
{% endblock www_content_box_2 %}

www/templates/portal/employer_object_public_view.html
{% extends "base/base_2col.html" %}

{% block www_title %}Business Profile - {{profile.business}}{% endblock www_title %}

{% block www_description %}
    <meta name="description" content="Get a free business listing on OutsourceFactor. Browse resumes and hire offshore employees. Download our incredible outsourcing guide for free." />
{% endblock www_description %}

{% block www_container_title %}
    {% include "portal/submenu.html" %}
{% endblock www_container_title %}

{% block www_content_box_1 %}
    {% include "employer/employer_profile_public_view.html" %}
{% endblock www_content_box_1 %}

{% block www_content_box_2 %}
    {% include "employer/employer_action_public_view.html" %}
{% endblock www_content_box_2 %}

www/templates/portal/job_object_public_view.html
{% extends "base/base_2col.html" %}

{% block www_title %}JobPost - {{job.title}} at {{profile.business}}{% endblock www_title %}

{% block www_description %}
    <meta name="description" content="OutsourceFactor lets you post jobs for free.  Recruit talented offshore employees.  Learn effective outsourcing strategies with out free training." />
{% endblock www_description %}

{% block www_container_title %}
    {% include "portal/submenu.html" %}
{% endblock www_container_title %}

{% block www_content_box_1 %}
    {% include "jobs/job_object_public_view.html" %}
{% endblock www_content_box_1 %}

{% block www_content_box_2 %}
    {% include "jobs/job_action_public_view.html" %}
{% endblock www_content_box_2 %}

www/templates/portal/search_jobs_view.html
{% extends "base/base_3col.html" %}

{% block www_title %}Home based jobs{% endblock www_title %}

{% block www_description %}
    <meta name="description" content="Get hired by an international company. Work from the comfort of your home. Post your resume and apply for home based jobs. Our free training book will amaze you." />
{% endblock www_description %}

{% block www_container_title %}
    {% include "portal/submenu.html" %}
{% endblock www_container_title %}

{% block www_content_box_1_1 %}
    <form id="job_search_form" class="search_form" action="{% url 'portal_job_search' %}" enctype="multipart/form-data" method="post" accept-charset="utf-8">{% csrf_token %}
        <fieldset>
            {{ form.as_p }}
        </fieldset>
        <input style="float:left" type="submit" value="{% trans "Search" %}" />
        <a href="{% url 'portal_job_search' %}" class="gray-button reset-button">Reset</a>
    </form>
    <br/><br/>
    <div class="fb-like-box" data-href="http://www.facebook.com/outsourcefactor" data-width="186" data-height="480" data-show-faces="true" data-border-color="#D7D7D7" data-stream="false" data-header="false"></div>
{% endblock www_content_box_1_1 %}

{% block www_content_box_1_2 %}
    {% if jobposts %}
        <div class="search_list">

            <div id="pagination_search_north">
                <span class="step-links-top">
                    {% if jobposts.has_previous %}
                        <a class="post_link " href="{% url 'portal_job_search_paginate' sk=search_key sp=jobposts.previous_page_number %}">
                            <img src="{{ STATIC_URL }}img/prev.png">
                        </a>
                    {% else %}
                        <img src="{{ STATIC_URL }}img/prev-gray.png">
                    {% endif %}


                    {% if jobposts.has_next %}
                        <a class="post_link" href="{% url 'portal_job_search_paginate' sk=search_key sp=jobposts.next_page_number %}">
                            <img src="{{ STATIC_URL }}img/next.png">
                        </a>
                    {% else %}
                        <img src="{{ STATIC_URL }}img/next-gray.png">
                    {% endif %}                
                </span>
                <span class="current-page-top">
                   {% if request.user.is_authenticated and request.user.is_staff %}({{total_result|intcomma}} job{{total_result|pluralize:",s"}}) -- {% endif %} [Page {{ jobposts.number }} of {{ jobposts.paginator.num_pages|roundplus }}]
                </span>
            </div>

            <ul class="browse_jobpost">
            {% for job in jobposts %}
                    <li class="e_block_jobpost border">
                        <div class="nobr">
                            <a class="e_jobpost" href="{% url 'employer_jobs_public_view' pk=job.id slug=job.get_slug %}" target="_blank">
                                {{ search_kw|highlight:job.title }}
                            </a>
                        </div>
                        <div class="nobr">
                            <span class="e_jobpost_company_name">
                                <img class="search_small_flags" src="{{ COMMON_DOWNLOADABLE_STATIC_URL }}images/flags/{{job.user.get_profile.country|lower}}_16.png" title="{{ job.user.get_profile.get_country_display }}"> {{ search_kw|highlight:job.user.get_profile.business }} 
                            </span>
                        </div>
                        <div class="nobr">
                            <p class="e_jobpost_details">
                                [ Type: {{job.get_employment_option_display|upper}} ] - [ Salary: {{job.get_wage_salary_display|upper}} {% if job.employment_option != job.JOB_OPTION_FREELANCE and "USD" in job.get_wage_salary_display%} PER MONTH{% endif %} ] - [ Starts: {% if job.is_past_due %}IMMEDIATELY{% else %}{{job.start_date|upper}}{% endif %} ]
                            </p>
                        </div>
                    
                        <p><u>Description:</u> {{ search_kw|highlight:job.description|truncatechars:210 }}
                    </li>
                {% endfor %}
            </ul> 

            <br/>
            <div id="pagination_search_south">
                <span class="current-page-bottom">
                    [Page {{ jobposts.number }} of {{ jobposts.paginator.num_pages|roundplus }}]
                </span>
                <span class="step-links-bottom">
                    {% if jobposts.has_previous %}
                        <a class="post_link " href="{% url 'portal_job_search_paginate' sk=search_key sp=jobposts.previous_page_number %}">
                            <img src="{{ STATIC_URL }}img/prev.png">
                        </a>
                    {% else %}
                        <img src="{{ STATIC_URL }}img/prev-gray.png">
                    {% endif %}
                    
                    {% if jobposts.has_next %}
                        <a class="post_link" href="{% url 'portal_job_search_paginate' sk=search_key sp=jobposts.next_page_number %}">
                            <img src="{{ STATIC_URL }}img/next.png">
                        </a>
                    {% else %}
                        <img src="{{ STATIC_URL }}img/next-gray.png">
                    {% endif %}                
                </span>
            </div>
            
        </div>
    {% else %}
        {% if specific_search %}
            <br/><br/>No match found for your search criteria. Please reset and try again.<br/><br/><hr/>
        {% else %}
            <br/><br/>
        {% endif %}
        <h2>Find the Perfect Online Job</h2>
        <br/>
        <p>Our job search engine is <strong>Clean, Simple and Fast</strong>. It's also completely free to use.  Search for jobs by skill or keywords. Explore the jobs that employers have posted and find one that matches your skills and interests. Then send a personal message to the employer to express your interest in the job.</p>

        <p><br/><strong>Keyword search examples:</strong>&nbsp;&nbsp;(case insensitive)<br/>wordpress&nbsp;&nbsp;blog = search for both <u>wordpress AND blog</u> in any order<br/>wordpress&nbsp;&nbsp;-blog = search for only <u>wordpress AND NOT blog</u> in any order<br/>"wordpress&nbsp;&nbsp;admin" = search for <u>wordpress&nbsp;&nbsp;admin</u> together, in this exact order</p>
                        
    {% endif %} 
    
{% endblock www_content_box_1_2 %}

{% block www_content_box_2 %}    
    <div class="likeplus_top_right_linx">
        <span class=" fb-like-box">
        <div class="fb-like" data-href="{{p_domain_base}}" data-send="true" data-layout="button_count" data-width="158" data-show-faces="false" data-font="verdana"></div>
        </span>
    </div>
    <div id="ads_box_right">
        {% if request.user.is_authenticated %}
            <a target="_blank" class="send2friend" href="mailto:?subject=Find online jobs at Outsourcefactor&amp;body=I found this job site useful and thought you might like it as well.%0d%0a%0d%0aIt has a lot of features including:%0d%0a%0d%0a+ Post Resume%0d%0a+ Jobs Search%0d%0a+ Bookmark Employers%0d%0a+ Contact Employers%0d%0a+ Social Login%0d%0a+ Youtube Video Pitch%0d%0a+ Access Training%0d%0a+ Free Accounts%0d%0a%0d%0aHere is the link:%0d%0a{{p_domain_base}}%0d%0a%0d%0aCheck it out today!">
                <img class="signup_ad"src="{{ STATIC_URL }}img/ads/employee_send2friends_160.gif" />
            </a>
        {% else %}
            <a href="{% url 'registration_register' %}" class="">
                <img class="signup_ad"src="{{ STATIC_URL }}img/ads/employee_signup_160.gif" />
            </a>        
        {% endif %}
    </div>
{% endblock www_content_box_2 %}

www/templates/portal/submenu.html
<div id="menu-sub-1" class="ui-tabs ui-widget">
    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-top">
        <div sytle="float:left">
        {% with request|get_left_portal_menu as menu %}
            {% for item in menu %}
                <li 
                    {% if item.selected %} 
                        class="ui-state-default ui-corner-top ui-tabs-selected ui-state-active" 
                    {% else %}
                        class="ui-state-default ui-corner-top ui-state-hover"
                    {% endif %}
                >
                    {% if item.editable %}
                        <a class="required_menu_field" href="{{item.url}}">{{ item.name }}</a>
                        <img src="{{STATIC_URL}}img/edit.png" />
                    {% else %}
                        <a href="{{item.url}}">{{ item.name }}</a>
                    {% endif %}
                </li>
            {% endfor %}
        {% endwith %}
        </div>
        <div style="float:right">
            {% with request|get_right_portal_menu as menu %}
                {% for item in menu %}
                    <li 
                        {% if item.selected %} 
                            class="ui-state-default ui-corner-top ui-tabs-selected ui-state-active" 
                        {% else %}
                            class="ui-state-default ui-corner-top ui-state-hover"
                        {% endif %}
                    >
                        <a href="{{item.url}}">{{ item.name }}</a>
                        {% if item.editable %}<img src="{{STATIC_URL}}img/edit.png" />{% endif %}
                    </li>
                {% endfor %}
            {% endwith %}
        </div>
    </ul>
    {% block www_notifications %}
        {% if messages %}
            {% for message in messages %}
                {% if forloop.last %}
                    <div id="msg_board"{% if message.tags %} class="{{ message.tags }}"{% endif %}>&raquo; {{ message }} &laquo;</div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endblock www_notifications %}
        
</div>

www/templates/portal/training_view.html
{% extends "base/base_2col.html" %}

{% block www_title %}Training Materials for {{profile.full_name}}{% endblock www_title %}

{% block www_container_title %}
    {% include "portal/submenu.html" %}
{% endblock www_container_title %}

{% block www_content_box_1 %}
    {% include "training/training_private_view.html" %}
{% endblock www_content_box_1 %}

{% block www_content_box_2 %}
    {% include "training/training_action_private_view.html" %}
{% endblock www_content_box_2 %}